spring:
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true


  h2:
    console:
      enabled: true
      path: /h2_db
  datasource:
    url: jdbc:h2:file:~/EDB/diary;DB_CLOSE_ON_EXIT=FALSE;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: yoon
    password: 1234


  redis:
    port: 6379  
    host: 127.0.0.1
    password: 1234
    

server:
  port: ${service_port:9000}
